#This ansible script will create a shared filesystem structure to deploy laravel tagged version.
#It allows us to share the .env file and the shared laravel objects
- hosts: webservers
  remote_user: root
    
  tasks:    
    - include_vars: variables.yml
      
#The shared files between releases      
    - name: Creates shared directories
      file:
        path: "{{ SITE_ROOT_FOLDER }}/{{ SITE_URL }}/{{item}}"
        state: directory
        # owner: www-data
        # group: www-data
        # mode: 0775
        recurse: yes
      loop:
        - releases
        - shared/storage/logs
        - shared/storage/framework/sessions
        - shared/storage/framework/testing
        - shared/storage/framework/views
        - shared/storage/framework/cache/data
                
    - name: Copy the .ENV file in shared folder
      template:
        src: .env.j2
        dest: /var/www/{{ SITE_URL }}/shared/.env
      become: true 

    - name: Copy the options-ssl-nginx.conf 
      ansible.builtin.copy:
        src: options-ssl-nginx.conf
        dest: /etc/letsencrypt/
      become: true      

    - name: Copy the serverbloc file 
      template:
        src: vulcan-hotel
        dest: /etc/nginx/sites-available/{{ SITE_URL }}/
      become: true   

    - name: generate Diffie-Hellman key
      shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048


    - name: Remove default nginx symlink
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      
    - name: Add  nginx symlink
      file:
        src: /etc/nginx/sites-available/{{ SITE_URL }}/vulcan-hotel # could be usefull to specify server block file
        dest: /etc/nginx/sites-enabled/{{ SITE_URL }} 
        state: link

# generate ssh key and it add it to github
